# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8f8bbded4ff7c7628cbd185e81129574"
application_url = "https://example.com"
embedded = true
name = "Simple Sales Notifications"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[webhooks]
api_version = "2026-04"

[build]
automatically_update_urls_on_dev = true
